//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleClient.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataInstance", Namespace="http://schemas.datacontract.org/2004/07/ClusterizationService")]
    [System.SerializableAttribute()]
    public partial class DataInstance : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[] attributesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int clusterField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[] attributes {
            get {
                return this.attributesField;
            }
            set {
                if ((object.ReferenceEquals(this.attributesField, value) != true)) {
                    this.attributesField = value;
                    this.RaisePropertyChanged("attributes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cluster {
            get {
                return this.clusterField;
            }
            set {
                if ((this.clusterField.Equals(value) != true)) {
                    this.clusterField = value;
                    this.RaisePropertyChanged("cluster");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IkMeans")]
    public interface IkMeans {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IkMeans/DoClusters", ReplyAction="http://tempuri.org/IkMeans/DoClustersResponse")]
        ConsoleClient.ServiceReference1.DataInstance[] DoClusters(ConsoleClient.ServiceReference1.DataInstance[] pDataset, int pClusterNum, double accuracy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IkMeans/DoClusters", ReplyAction="http://tempuri.org/IkMeans/DoClustersResponse")]
        System.Threading.Tasks.Task<ConsoleClient.ServiceReference1.DataInstance[]> DoClustersAsync(ConsoleClient.ServiceReference1.DataInstance[] pDataset, int pClusterNum, double accuracy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IkMeansChannel : ConsoleClient.ServiceReference1.IkMeans, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IkMeansClient : System.ServiceModel.ClientBase<ConsoleClient.ServiceReference1.IkMeans>, ConsoleClient.ServiceReference1.IkMeans {
        
        public IkMeansClient() {
        }
        
        public IkMeansClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IkMeansClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IkMeansClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IkMeansClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ConsoleClient.ServiceReference1.DataInstance[] DoClusters(ConsoleClient.ServiceReference1.DataInstance[] pDataset, int pClusterNum, double accuracy) {
            return base.Channel.DoClusters(pDataset, pClusterNum, accuracy);
        }
        
        public System.Threading.Tasks.Task<ConsoleClient.ServiceReference1.DataInstance[]> DoClustersAsync(ConsoleClient.ServiceReference1.DataInstance[] pDataset, int pClusterNum, double accuracy) {
            return base.Channel.DoClustersAsync(pDataset, pClusterNum, accuracy);
        }
    }
}
